### ISSUE TITLE
Loading blendshape gltf.

### ISSUE THREAD

**Issue by wolfviking0** [SaschaWillems/Vulkan-glTF-PBR#6] opened 2018-05-07 01:19 UTC
Did you try to load some gltf model with blend shape animation ??

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/README.md

**Comment by SaschaWillems** [comment] 2018-05-07 16:57
There's no animation support yet. It's on my list, but no ETA.

**Comment by sjfricke** [comment] 2018-05-13 02:59
@wolfviking0 I actually was in need of blend shapes for another project of mind, I have got a good way on this implementation with future improvements to come

https://github.com/sjfricke/Vulkan-glTF-Morph-Target

**Comment by syoyo** [comment] 2020-02-22 13:04
I have combined Vulkan-glTF-Morph-Target and Vulkan-glTF-PBR(skin) in my internal test app and confirmed it works well.

I'm considering to send a PR to support Morph. Before of it, I have a question.

@sjfricke 's implementation uses SSBO for morph data. Using SSBO for morph data may be flexible, but it makes shader and vulkan data structure complex and codes become difficult to read and maintain(and sometimes it tend to become the source of various bugs(I've faced the out-of-bounds access error for some glTF scene, it was difficult to debug)).

Using VertexAttribute for morph data may be much simpler and clean, but it cannot support sparse morph target data. Also, the number of morph targets may be limited by Vulkan HW limits(although, at least we should be able to support up to 100 morph targets on low-end and mobile GPUs(Mali, Adreno)).

We could also use Texture(or Image) as an morph data storage.

@SaschaWillems how do you think? Do you have any good practice how to implement Morph in Vulkan?

**Comment by SaschaWillems** [comment] 2020-02-29 09:22
@syoyo: That sounds awesome. And even though code for using SSBOs may be more complex I'd prefer using SSBOs for their flexibility. So feel free to open a PR :)

**Comment by syoyo** [comment] 2020-02-29 11:16
@SaschaWillems OK, will use SSBO. It requires some amount of code and data structure refactoring, so probably PR will be sent around the end of March, 2020

**Comment by SaschaWillems** [comment] 2020-03-01 08:09
If the SSBO way is too complex or requires too much effort, the other options would be fine too. So feel free to choose the option that suits you best :)

**Comment by questgugou** [comment] 2022-12-29 09:36
good idea

**Comment by apchenstu** [comment] 2024-09-23 14:50
> @SaschaWillems OK, will use SSBO. It requires some amount of code and data structure refactoring, so probably PR will be sent around the end of March, 2020

It will be very helpful if you can share your implementation!

**Comment by SaschaWillems** [comment] 2024-11-11 17:48
Closing this due to inacvitiy.

**Closed by SaschaWillems** 2024-11-11 17:48 UTC
